/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hardware_windmill */

#ifndef _Included_Hardware_windmill
#define _Included_Hardware_windmill
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hardware_windmill
 * Method:    energyProduction
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Hardware_windmill_energyProduction
  (JNIEnv *, jclass);

/*
 * Class:     Hardware_windmill
 * Method:    turnOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Hardware_windmill_turnOn
  (JNIEnv *, jclass, jint);

/*
 * Class:     Hardware_windmill
 * Method:    isOn
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Hardware_windmill_isOn
  (JNIEnv *, jclass);

/*
 * Class:     Hardware_windmill
 * Method:    error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Hardware_windmill_error
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_Hardware_windmill_serialNumber
(JNIEnv *var, jclass var2);

#ifdef __cplusplus
}
#endif
#endif
