//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace Manufacturer_App_IS.FrontEndWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServices/", ConfigurationName="FrontEndWebService.FrontEndWebService")]
    public interface FrontEndWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/loginUserRequest", ReplyAction="http://WebServices/FrontEndWebService/loginUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.loginUserResponse> loginUserAsync(Manufacturer_App_IS.FrontEndWebService.loginUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getUserDevicesRequest", ReplyAction="http://WebServices/FrontEndWebService/getUserDevicesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getUserDevicesResponse> getUserDevicesAsync(Manufacturer_App_IS.FrontEndWebService.getUserDevicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/createDBRequest", ReplyAction="http://WebServices/FrontEndWebService/createDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.createDBResponse> createDBAsync(Manufacturer_App_IS.FrontEndWebService.createDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/addDeviceRequest", ReplyAction="http://WebServices/FrontEndWebService/addDeviceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addDeviceResponse> addDeviceAsync(Manufacturer_App_IS.FrontEndWebService.addDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getDeviceHistoryRequest", ReplyAction="http://WebServices/FrontEndWebService/getDeviceHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryResponse> getDeviceHistoryAsync(Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getDeviceTypesRequest", ReplyAction="http://WebServices/FrontEndWebService/getDeviceTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getDeviceTypesResponse> getDeviceTypesAsync(Manufacturer_App_IS.FrontEndWebService.getDeviceTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getUserHistoryRequest", ReplyAction="http://WebServices/FrontEndWebService/getUserHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getUserHistoryResponse> getUserHistoryAsync(Manufacturer_App_IS.FrontEndWebService.getUserHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/loginManufacturerRequest", ReplyAction="http://WebServices/FrontEndWebService/loginManufacturerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.loginManufacturerResponse> loginManufacturerAsync(Manufacturer_App_IS.FrontEndWebService.loginManufacturerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/addUserRequest", ReplyAction="http://WebServices/FrontEndWebService/addUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addUserResponse> addUserAsync(Manufacturer_App_IS.FrontEndWebService.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/addManufacturerRequest", ReplyAction="http://WebServices/FrontEndWebService/addManufacturerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addManufacturerResponse> addManufacturerAsync(Manufacturer_App_IS.FrontEndWebService.addManufacturerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginUser", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class loginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passwordHash;
        
        public loginUserRequest() {
        }
        
        public loginUserRequest(string user, string passwordHash) {
            this.user = user;
            this.passwordHash = passwordHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginUserResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class loginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public loginUserResponse() {
        }
        
        public loginUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDevices", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public getUserDevicesRequest() {
        }
        
        public getUserDevicesRequest(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDevicesResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getUserDevicesResponse() {
        }
        
        public getUserDevicesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDB", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class createDBRequest {
        
        public createDBRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDBResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class createDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createDBResponse() {
        }
        
        public createDBResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDevice", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int serialNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string friendlyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int deviceType;
        
        public addDeviceRequest() {
        }
        
        public addDeviceRequest(int serialNumber, string userName, string model, string friendlyName, int deviceType) {
            this.serialNumber = serialNumber;
            this.userName = userName;
            this.model = model;
            this.friendlyName = friendlyName;
            this.deviceType = deviceType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addDeviceResponse() {
        }
        
        public addDeviceResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeviceHistory", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getDeviceHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serialNumber;
        
        public getDeviceHistoryRequest() {
        }
        
        public getDeviceHistoryRequest(string serialNumber) {
            this.serialNumber = serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeviceHistoryResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getDeviceHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getDeviceHistoryResponse() {
        }
        
        public getDeviceHistoryResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeviceTypes", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getDeviceTypesRequest {
        
        public getDeviceTypesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeviceTypesResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getDeviceTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getDeviceTypesResponse() {
        }
        
        public getDeviceTypesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserHistory", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public getUserHistoryRequest() {
        }
        
        public getUserHistoryRequest(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserHistoryResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getUserHistoryResponse() {
        }
        
        public getUserHistoryResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginManufacturer", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class loginManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hash;
        
        public loginManufacturerRequest() {
        }
        
        public loginManufacturerRequest(string userName, string hash) {
            this.userName = userName;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginManufacturerResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class loginManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public loginManufacturerResponse() {
        }
        
        public loginManufacturerResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUser", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int telephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string residence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hash;
        
        public addUserRequest() {
        }
        
        public addUserRequest(string userName, string name, int telephone, string residence, string hash) {
            this.userName = userName;
            this.name = name;
            this.telephone = telephone;
            this.residence = residence;
            this.hash = hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addUserResponse() {
        }
        
        public addUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addManufacturer", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addManufacturerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Telephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Residence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Hash;
        
        public addManufacturerRequest() {
        }
        
        public addManufacturerRequest(string UserName, string Name, int Telephone, int Type, string Residence, string Hash) {
            this.UserName = UserName;
            this.Name = Name;
            this.Telephone = Telephone;
            this.Type = Type;
            this.Residence = Residence;
            this.Hash = Hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addManufacturerResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addManufacturerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addManufacturerResponse() {
        }
        
        public addManufacturerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FrontEndWebServiceChannel : Manufacturer_App_IS.FrontEndWebService.FrontEndWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrontEndWebServiceClient : System.ServiceModel.ClientBase<Manufacturer_App_IS.FrontEndWebService.FrontEndWebService>, Manufacturer_App_IS.FrontEndWebService.FrontEndWebService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FrontEndWebServiceClient() : 
                base(FrontEndWebServiceClient.GetDefaultBinding(), FrontEndWebServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.FrontEndWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrontEndWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FrontEndWebServiceClient.GetBindingForEndpoint(endpointConfiguration), FrontEndWebServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrontEndWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FrontEndWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrontEndWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FrontEndWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FrontEndWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.loginUserResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.loginUserAsync(Manufacturer_App_IS.FrontEndWebService.loginUserRequest request) {
            return base.Channel.loginUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.loginUserResponse> loginUserAsync(string user, string passwordHash) {
            Manufacturer_App_IS.FrontEndWebService.loginUserRequest inValue = new Manufacturer_App_IS.FrontEndWebService.loginUserRequest();
            inValue.user = user;
            inValue.passwordHash = passwordHash;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).loginUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getUserDevicesResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.getUserDevicesAsync(Manufacturer_App_IS.FrontEndWebService.getUserDevicesRequest request) {
            return base.Channel.getUserDevicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getUserDevicesResponse> getUserDevicesAsync(string userName) {
            Manufacturer_App_IS.FrontEndWebService.getUserDevicesRequest inValue = new Manufacturer_App_IS.FrontEndWebService.getUserDevicesRequest();
            inValue.userName = userName;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).getUserDevicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.createDBResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.createDBAsync(Manufacturer_App_IS.FrontEndWebService.createDBRequest request) {
            return base.Channel.createDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.createDBResponse> createDBAsync() {
            Manufacturer_App_IS.FrontEndWebService.createDBRequest inValue = new Manufacturer_App_IS.FrontEndWebService.createDBRequest();
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).createDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addDeviceResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.addDeviceAsync(Manufacturer_App_IS.FrontEndWebService.addDeviceRequest request) {
            return base.Channel.addDeviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addDeviceResponse> addDeviceAsync(int serialNumber, string userName, string model, string friendlyName, int deviceType) {
            Manufacturer_App_IS.FrontEndWebService.addDeviceRequest inValue = new Manufacturer_App_IS.FrontEndWebService.addDeviceRequest();
            inValue.serialNumber = serialNumber;
            inValue.userName = userName;
            inValue.model = model;
            inValue.friendlyName = friendlyName;
            inValue.deviceType = deviceType;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).addDeviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.getDeviceHistoryAsync(Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryRequest request) {
            return base.Channel.getDeviceHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryResponse> getDeviceHistoryAsync(string serialNumber) {
            Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryRequest inValue = new Manufacturer_App_IS.FrontEndWebService.getDeviceHistoryRequest();
            inValue.serialNumber = serialNumber;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).getDeviceHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getDeviceTypesResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.getDeviceTypesAsync(Manufacturer_App_IS.FrontEndWebService.getDeviceTypesRequest request) {
            return base.Channel.getDeviceTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getDeviceTypesResponse> getDeviceTypesAsync() {
            Manufacturer_App_IS.FrontEndWebService.getDeviceTypesRequest inValue = new Manufacturer_App_IS.FrontEndWebService.getDeviceTypesRequest();
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).getDeviceTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getUserHistoryResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.getUserHistoryAsync(Manufacturer_App_IS.FrontEndWebService.getUserHistoryRequest request) {
            return base.Channel.getUserHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.getUserHistoryResponse> getUserHistoryAsync(string userName) {
            Manufacturer_App_IS.FrontEndWebService.getUserHistoryRequest inValue = new Manufacturer_App_IS.FrontEndWebService.getUserHistoryRequest();
            inValue.userName = userName;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).getUserHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.loginManufacturerResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.loginManufacturerAsync(Manufacturer_App_IS.FrontEndWebService.loginManufacturerRequest request) {
            return base.Channel.loginManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.loginManufacturerResponse> loginManufacturerAsync(string userName, string hash) {
            Manufacturer_App_IS.FrontEndWebService.loginManufacturerRequest inValue = new Manufacturer_App_IS.FrontEndWebService.loginManufacturerRequest();
            inValue.userName = userName;
            inValue.hash = hash;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).loginManufacturerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addUserResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.addUserAsync(Manufacturer_App_IS.FrontEndWebService.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addUserResponse> addUserAsync(string userName, string name, int telephone, string residence, string hash) {
            Manufacturer_App_IS.FrontEndWebService.addUserRequest inValue = new Manufacturer_App_IS.FrontEndWebService.addUserRequest();
            inValue.userName = userName;
            inValue.name = name;
            inValue.telephone = telephone;
            inValue.residence = residence;
            inValue.hash = hash;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addManufacturerResponse> Manufacturer_App_IS.FrontEndWebService.FrontEndWebService.addManufacturerAsync(Manufacturer_App_IS.FrontEndWebService.addManufacturerRequest request) {
            return base.Channel.addManufacturerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Manufacturer_App_IS.FrontEndWebService.addManufacturerResponse> addManufacturerAsync(string UserName, string Name, int Telephone, int Type, string Residence, string Hash) {
            Manufacturer_App_IS.FrontEndWebService.addManufacturerRequest inValue = new Manufacturer_App_IS.FrontEndWebService.addManufacturerRequest();
            inValue.UserName = UserName;
            inValue.Name = Name;
            inValue.Telephone = Telephone;
            inValue.Type = Type;
            inValue.Residence = Residence;
            inValue.Hash = Hash;
            return ((Manufacturer_App_IS.FrontEndWebService.FrontEndWebService)(this)).addManufacturerAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.FrontEndWebServicePort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.FrontEndWebServicePort)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/IS_Trab2/FrontEndWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return FrontEndWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.FrontEndWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return FrontEndWebServiceClient.GetEndpointAddress(EndpointConfiguration.FrontEndWebServicePort);
        }
        
        public enum EndpointConfiguration {
            
            FrontEndWebServicePort,
        }
    }
}
