//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace Client_App_IS.FrontEndService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServices/", ConfigurationName="FrontEndService.FrontEndWebService")]
    public interface FrontEndWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getUserDevicesRequest", ReplyAction="http://WebServices/FrontEndWebService/getUserDevicesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getUserDevicesResponse> getUserDevicesAsync(Client_App_IS.FrontEndService.getUserDevicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/addUserRequest", ReplyAction="http://WebServices/FrontEndWebService/addUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.addUserResponse> addUserAsync(Client_App_IS.FrontEndService.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/addDeviceRequest", ReplyAction="http://WebServices/FrontEndWebService/addDeviceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.addDeviceResponse> addDeviceAsync(Client_App_IS.FrontEndService.addDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getUserHistoryRequest", ReplyAction="http://WebServices/FrontEndWebService/getUserHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getUserHistoryResponse> getUserHistoryAsync(Client_App_IS.FrontEndService.getUserHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/getDeviceHistoryRequest", ReplyAction="http://WebServices/FrontEndWebService/getDeviceHistoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getDeviceHistoryResponse> getDeviceHistoryAsync(Client_App_IS.FrontEndService.getDeviceHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/FrontEndWebService/createDBRequest", ReplyAction="http://WebServices/FrontEndWebService/createDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.createDBResponse> createDBAsync(Client_App_IS.FrontEndService.createDBRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDevices", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public getUserDevicesRequest() {
        }
        
        public getUserDevicesRequest(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDevicesResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getUserDevicesResponse() {
        }
        
        public getUserDevicesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUser", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string residence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int telephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public addUserRequest() {
        }
        
        public addUserRequest(string name, string residence, int telephone, string userName) {
            this.name = name;
            this.residence = residence;
            this.telephone = telephone;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addUserResponse() {
        }
        
        public addUserResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDevice", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int deviceType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string friendlyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int serialNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public addDeviceRequest() {
        }
        
        public addDeviceRequest(int deviceType, string friendlyName, string model, int serialNumber, string userName) {
            this.deviceType = deviceType;
            this.friendlyName = friendlyName;
            this.model = model;
            this.serialNumber = serialNumber;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class addDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public addDeviceResponse() {
        }
        
        public addDeviceResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserHistory", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        public getUserHistoryRequest() {
        }
        
        public getUserHistoryRequest(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserHistoryResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getUserHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getUserHistoryResponse() {
        }
        
        public getUserHistoryResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeviceHistory", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getDeviceHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serialNumber;
        
        public getDeviceHistoryRequest() {
        }
        
        public getDeviceHistoryRequest(string serialNumber) {
            this.serialNumber = serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeviceHistoryResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class getDeviceHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getDeviceHistoryResponse() {
        }
        
        public getDeviceHistoryResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDB", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class createDBRequest {
        
        public createDBRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDBResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class createDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public createDBResponse() {
        }
        
        public createDBResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FrontEndWebServiceChannel : Client_App_IS.FrontEndService.FrontEndWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrontEndWebServiceClient : System.ServiceModel.ClientBase<Client_App_IS.FrontEndService.FrontEndWebService>, Client_App_IS.FrontEndService.FrontEndWebService {
        
        public FrontEndWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getUserDevicesResponse> Client_App_IS.FrontEndService.FrontEndWebService.getUserDevicesAsync(Client_App_IS.FrontEndService.getUserDevicesRequest request) {
            return base.Channel.getUserDevicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getUserDevicesResponse> getUserDevicesAsync(string userName) {
            Client_App_IS.FrontEndService.getUserDevicesRequest inValue = new Client_App_IS.FrontEndService.getUserDevicesRequest();
            inValue.userName = userName;
            return ((Client_App_IS.FrontEndService.FrontEndWebService)(this)).getUserDevicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.addUserResponse> Client_App_IS.FrontEndService.FrontEndWebService.addUserAsync(Client_App_IS.FrontEndService.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_App_IS.FrontEndService.addUserResponse> addUserAsync(string name, string residence, int telephone, string userName) {
            Client_App_IS.FrontEndService.addUserRequest inValue = new Client_App_IS.FrontEndService.addUserRequest();
            inValue.name = name;
            inValue.residence = residence;
            inValue.telephone = telephone;
            inValue.userName = userName;
            return ((Client_App_IS.FrontEndService.FrontEndWebService)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.addDeviceResponse> Client_App_IS.FrontEndService.FrontEndWebService.addDeviceAsync(Client_App_IS.FrontEndService.addDeviceRequest request) {
            return base.Channel.addDeviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_App_IS.FrontEndService.addDeviceResponse> addDeviceAsync(int deviceType, string friendlyName, string model, int serialNumber, string userName) {
            Client_App_IS.FrontEndService.addDeviceRequest inValue = new Client_App_IS.FrontEndService.addDeviceRequest();
            inValue.deviceType = deviceType;
            inValue.friendlyName = friendlyName;
            inValue.model = model;
            inValue.serialNumber = serialNumber;
            inValue.userName = userName;
            return ((Client_App_IS.FrontEndService.FrontEndWebService)(this)).addDeviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getUserHistoryResponse> Client_App_IS.FrontEndService.FrontEndWebService.getUserHistoryAsync(Client_App_IS.FrontEndService.getUserHistoryRequest request) {
            return base.Channel.getUserHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getUserHistoryResponse> getUserHistoryAsync(string userName) {
            Client_App_IS.FrontEndService.getUserHistoryRequest inValue = new Client_App_IS.FrontEndService.getUserHistoryRequest();
            inValue.userName = userName;
            return ((Client_App_IS.FrontEndService.FrontEndWebService)(this)).getUserHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getDeviceHistoryResponse> Client_App_IS.FrontEndService.FrontEndWebService.getDeviceHistoryAsync(Client_App_IS.FrontEndService.getDeviceHistoryRequest request) {
            return base.Channel.getDeviceHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_App_IS.FrontEndService.getDeviceHistoryResponse> getDeviceHistoryAsync(string serialNumber) {
            Client_App_IS.FrontEndService.getDeviceHistoryRequest inValue = new Client_App_IS.FrontEndService.getDeviceHistoryRequest();
            inValue.serialNumber = serialNumber;
            return ((Client_App_IS.FrontEndService.FrontEndWebService)(this)).getDeviceHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_App_IS.FrontEndService.createDBResponse> Client_App_IS.FrontEndService.FrontEndWebService.createDBAsync(Client_App_IS.FrontEndService.createDBRequest request) {
            return base.Channel.createDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_App_IS.FrontEndService.createDBResponse> createDBAsync() {
            Client_App_IS.FrontEndService.createDBRequest inValue = new Client_App_IS.FrontEndService.createDBRequest();
            return ((Client_App_IS.FrontEndService.FrontEndWebService)(this)).createDBAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
